version: "3.7"
services:
  webapp:
    build: tomcat
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: ghqkr327598!!
      MYSQL_DB: db01

  database:
    build: database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ghqkr327598!!
      MYSQL_DATABASE: db01
